.PHONY: clean All

All:
	@echo "----------Building project:[ delme - Debug ]----------"
	@cd "delme" && "$(MAKE)" -f  "delme.mk"
clean:
	@echo "----------Cleaning project:[ delme - Debug ]----------"
	@cd "delme" && "$(MAKE)" -f  "delme.mk" clean
